#!/usr/bin/env python2
'''
Create a dat file using the function as input
'''

import numpy as np;
from cStringIO import StringIO;
def mkdat2d(F,xr=(-30e-4,20e-4, 50j),
            yr=(-30e-4,20e-4, 50j),fname=None):
    X,Y = np.mgrid[ xr[0]:xr[1]:xr[2],
                    yr[0]:yr[1]:yr[2]]
    xlen,ylen = X.shape;
    S=F(X,Y);
    def writeout(f):
        f.write("# generated by mkdat.py\n");
        f.write("# first, dimensions\n\n");
        f.write( (("{} ")*2+'\n\n').format(xlen,ylen));
        f.write("# now, cells\n\n");
        f.write("# x:\n")
        np.savetxt(f, X[:,0], newline=' '); f.write("\n");
        f.write("# y:\n")
        np.savetxt(f, Y[0,:], newline=' '); f.write("\n");
        f.write("\n# now, the actual data\n\n")
        np.savetxt(f,S[:,:]);
        pass;
    if fname == None:
        f = StringIO();
        writeout(f);
        ret=f.getvalue();
        f.close();
        return ret;
    elif type(fname) == str:
        f = open(fname,'w');
        writeout(f);
        f.close()
    else:
        writeout(f);
    pass;

    
def mkdat(F,xr=(-30e-4,20e-4, 20j),
            yr=(-20e-4,20e-4, 20j),
            zr=(-10e-4,10e-4, 20j),
            fname=None):
    X,Y,Z = np.mgrid[ xr[0]:xr[1]:xr[2],
                      yr[0]:yr[1]:yr[2],
                      zr[0]:zr[1]:zr[2]];
    S=F(X,Y,Z);
    xlen = len(X[:,0,0]);
    ylen = len(Y[0,:,0]);
    zlen = len(Z[0,0,:]);

    def writeout(f):
        f.write("# generated by mkdat.py\n");
        f.write("# first, dimensions\n\n");
        f.write( (("{} ")*3+'\n\n').format(xlen,ylen,zlen));
        f.write("# now, cells\n\n");
        f.write("# x:\n")
        np.savetxt(f, X[:,0,0], newline=' '); f.write("\n");
        f.write("# y:\n")
        np.savetxt(f, Y[0,:,0], newline=' '); f.write("\n");
        f.write("# z:\n")
        np.savetxt(f, Z[0,0,:], newline=' '); f.write("\n");
        f.write("\n# now, the actual data\n\n")
        for i in xrange(zlen):
            np.savetxt(f,S[:,:,i]);
        pass;
    
    close = True;
    if fname == None:
        f = StringIO();
        writeout(f);
        ret=f.getvalue();
        f.close();
        return ret;
    elif type(fname) == str:
        f = open(fname,'w');
        writeout(f);
        f.close()
    else:
        writeout(f);
    pass;
    
if __name__ == '__main__':
    f=lambda x,y,z: x+y+z;
    s=mkdat(f,xr=(  1,  4,  1),
              yr=( 10, 40, 20),
              zr=(100,400,30));
    print(s);  
