#!/usr/bin/env bash
PREFIX=RhoN10_
POSTFIX=.s
while getopts ':hp:e:' opt; do
    case $opt in
        p)
            PREFIX=$OPTARG
            shift $((OPTIND-1))
            ;;
        e)  
            POSTFIX=$OPTARG
            shift $((OPTIND-1))
            ;;
        h)
            echo "usage: ch [-p PREFIX | -h | -e POSTFIX ] [<begin> [<end> [<step>]]]"
            exit 0
            ;;
        \?)
            echo "Invalid option: -$optarg">&2
            exit 1
            ;;
        :)
            echo "Option -$optarg requires an argument.">&2
            exit 1
            ;;
    esac
done
BEGIN=$( [ -n "$1" ] && echo $1 || echo 2)
END=$( [ -n "$2" ] && echo $2 || echo 2500)
STEP=$( [ -n "$3" ] && echo $3 || echo 2)

for ((i=$START; i<=$END; i+=$STEP)); do
    if [ ! -f  ${PREFIX}${i}${POSTFIX} ]; then
        echo $i;
    fi
done;
