#!/usr/bin/env bash
USAGE="Copies pmovie reading scripts and makes pbs files. Makes the files in the working directory.

usage: ./pmovie-prep [-h -n <numberofnodes> -s <server>] <pmovie-dir> [<reader-dir>]"
NODES=1
SERVER="ramses"
while getopts ':hn:s:' opt; do
      case $opt in
          h)
              echo "Script to prepare pmovies for trajectories."
              echo
              echo $USAGE
              exit 0
              ;;
          n)
              NODES=$OPTARG
              shift $((OPTIND-1))
              ;;
          s)
              SERVER=$OPTARG
              shift $((OPTIND-1))
              ;;
              
          \?)
              echo "Invalid option: $OPTARG">&2
              exit 1
              ;;
          :)
              echo "Option -$OPTARG requires an argument.">&2
              exit 1
              ;;
      esac
done

DEST=$( [ -n "$1" ] && echo $1)
[ -z "$DEST" ] && echo $USAGE && exit 1;
RDDIR=$( [ -n "$2" ]  && echo $2 || echo ".." )
cp $RDDIR/lspreader.py $RDDIR/misc.py $RDDIR/pmov.py $DEST
cp $RDDIR/pmovie-reader/* $RDDIR/misc.py ./

./pmovie-pbsgen.py --server=$SERVER --nodes=$NODES $DEST
PBSES=$(ls | grep 'pmovie-conv.*.pbs$')
#generating the reader script. Calling it unleashes the hounds.
echo "#!/bin/bash

for i in $PBSES; do
    qsub \$i;
done;
">pmovreader.sh
chmod +x pmovreader.sh
