#!/usr/bin/env bash
USAGE="Copies pmovie reading scripts and makes pbs files.

Usage: 
    ./pmovie-prep [options] <pmovie-dir> [<lspreader-dir> [<pbsoutput-dir>]]
Options:
    -h                   Print help
    -n N                 Specify number N of nodes. 1 is usually enough for
                         2D sims and is the default.
    -s SERVER            Specify server. Current valid ones are \"ramses\" and \"glenn\".
                         \"ramses\" is default.
    -N RAMSESNODE        Run only on the node RAMSESNODE. Default does not use this.
"
NODES=1
SERVER="ramses"
RDDIR="/home/ngirmang.1/lspreader"
CONDA="/home/ngirmang.1/conda"
RAMSESNODE=
while getopts ':hn:s:N' opt; do
      case $opt in
          h)
              echo $USAGE
              exit 0
              ;;
          n)
              NODES=$OPTARG
              shift $((OPTIND-1))
              ;;
          N)
              RAMSESNODE=$OPTARG
              shift $((OPTIND-1))
              ;;
          s)
              SERVER=$OPTARG
              shift $((OPTIND-1))
              ;;
              
          \?)
              echo "Invalid option: $OPTARG">&2
              exit 1
              ;;
          :)
              echo "Option -$OPTARG requires an argument.">&2
              exit 1
              ;;
      esac
done

source $CONDA
DEST=$( [ -n "$1" ] && echo $1)
[ -z "$DEST" ] && echo $USAGE && exit 1;
RDDIR=$( [ -n "$2" ]  && echo $2 || echo ".." )
OUTDIR=$( [ -n "$3" ] && echo $3 ||  echo "." )
cp $RDDIR/lspreader.py $RDDIR/misc.py $RDDIR/pmov.py $DEST
cp $RDDIR/pmovie-reader/* $RDDIR/misc.py $OUTDIR/
if [ $SERVER == "ramses" ] && [ -n "$RAMSESNODE" ]; then
    RAMSESNODE="--ramses-node=$RAMSESNODE";
fi

./pmovie-pbsgen-exp.py --server=$SERVER --nodes=$NODES --outdir=$OUTDIR \
                       --ramses-node=$RAMSESNODE $DEST
PBSES=$(ls | grep 'pmovie-conv.*.pbs$')
#generating the reader script. Calling it unleashes the hounds.
echo "#!/bin/bash

for i in $PBSES; do
    qsub \$i;
done;
">pmovreader.sh
chmod +x pmovreader.sh
